[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohd Saif", email = "saifofficial0778@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
    "tavily>=1.1.0",
]

[project.scripts]
agent = "agent:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
