[project]
name = "day13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohd Saif", email = "saifofficial0778@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
day13 = "day13:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
